### PR TITLE
Searching at scale.

### PR DESCRIPTION
**Pull request by dokterbob**

### CODE REVIEW

**Comment by dokterbob** [comment]
@Szeket CSS challenge! ❤️ if you can get these images side-by-side!
image

**Comment by Szeket** [comment]
file:///home/oszka/Pictures/Screenshots/Screenshot%20from%202023-04-18%2019-19-59.png

Could it be a table?

**Review by Szeket — APPROVED** [review]

**Comment by dokterbob** [comment]
@Szeket 
> Could it be a table?
If all else fails.

Did you try `float`?

(This morning) I imagined something like this:
```html
<div> <!-- container, to prevent image floating left or right from text -->
  <figure style="width: 30vb; float: left; text-align: center;">
  	<img src="https://bafybeigq2kkb4xduw7yq64pnw6v6khzn3g2nv2wt2f2cc4kb2kspkoevhi.on.fleek.co/assets/images/2023-04-18-searching-at-scale/Untitled%2019.png">
    <figcaption>Bananas are healthy</figcaption>
  </figure>

  <figure style="width: 30vb; float: right; text-align: center;">
  	<img src="https://bafybeigq2kkb4xduw7yq64pnw6v6khzn3g2nv2wt2f2cc4kb2kspkoevhi.on.fleek.co/assets/images/2023-04-18-searching-at-scale/Untitled%2018.png">
    <figcaption>Doggies are cute</figcaption>
  </figure>
</div>
```

**Comment by Szeket** [comment]
These figures look kinda bad still. Very large. Also not good on mobile view.

**Pull request merged**
